FROM node:10

WORKDIR /app

# העתק קבצי package.json ו-package-lock.json
COPY package*.json ./

# התקן תלויות
RUN npm install

# העתק את שאר קוד המקור
COPY . .

# הרץ את הבדיקות
CMD ["npm", "test", "--", "--watchAll=false"]