FROM node:14-alpine

WORKDIR /app

# התקן את הכלים הדרושים לבניית node-sass
RUN apk add --no-cache python3 make g++ && ln -sf python3 /usr/bin/python

# העתק קבצי package.json ו-package-lock.json
COPY package*.json ./

# התקן תלויות
RUN npm install

# העתק את שאר קוד המקור
COPY . .

# הרץ את הבדיקות
CMD ["npm", "test", "--", "--watchAll=false"]